#categories:


category = {"afghani": "afghani",
            "african": "african",
            "senegalese": "african",
            "southafrican": "african",
            "newamerican":"newamerican",
            "tradamerican":"tradamerican",
            "arabian":"arabian",
            "armenian": "armenian",
            "argentine": "argentine",
            "asianfusion":"asianfusion",
            "australian": "australian",
            "austrian": "australian",
            "bangladeshi":"bangladeshi",
            "bbq":"tradamerican",
            "basque":"basque",
            "belgian":"belgian",
            "brasseries":"french",
            "brazilian": "brazilian",
            "breakfast_brunch": "tradamerican",
            "british":"british",
            "buffets": "seafood",
            "burgers": "tradamerican",
            "burmese":"burmese",
            "cafes":"cafes",
            "themedcafes": "cafes",
            "cafeteria": "cafes",
            "cajun": "cajun",
            "cambodian":"cambodian",
            "caribbean":"caribbean",
            "dominican": "caribbean",
            "haitian": "haitian",
            "puertorican": "caribbean",
            "trinidadian": "caribbean",
            "catalan": "french",
            "cheesesteaks":"tradamerican",
            "chickenshop":"tradamerican",
            "chicken_wings":"tradamerican",
            "chinese":"chinese",
            "cantonese":"chinese",
            "dimsum":"chinese",
            "hainan":"chinese",
            "shanghainese": "chinese",
            "szechuan":"chinese",
            "comfortfood": "newamerican",
            "creperies": "cafes",
            "cuban":"cuban",
            "czech": "czech",
            "delis":"fastfood",
            "diners":"dinner",
            "dinnertheater":"dinner",
            "ethiopian":"african",
            "hotdogs": "fastfood",
            "filipino":"filipino",
            "fishnchips":"seafood",
            "foodstands": "fastfood",
            "fondue": "newamerican",
            "food_court": "fastfood",
            "french":"french",
            "mauritius":"african",
            "reunion": "dinner",
            "gastropubs": "newamerican",
            "german": "german",
            "gluten_free": "newamerican",
            "greek":"greek",
            "guamanian":"guamanian",
            "halal":"italian",
            "hawaiian":"hawaiian",
            "himalayan":"indian",
            "honduran":"honduran",
            "hkcafe":"chinese",
            "hotdog":"fastfood",
            "hotpot":"chinese",
            "hungarian":"hungarian",
            "iberian":"african",
            "indpak":"indian",
            "indonesian":"indonesian",
            "irish":"irish",
            "italian":"italian",
            "calabrian":"italian",
            "sardinian":"mediterranean",
            "tuscan":"italian",
            "japanese":"japanese",
            "conveyorsushi":"japanese",
            "izakaya":"japanese",
            "ramen":"japanese",
            "teppanyaki":"japanese",
            "kebab": "indian",
            "korean":"korean",
            "kosher":"fastfood",
            "laotian":"laotian",
            "latin":"latin",
            "colombian":"colombian",
            "salvadoran": "caribbean",
            "venezuelan":"caribbean",
            "raw_food":"seafood",
            "malaysian":"malaysian",
            "mediterranean":"mediterranean",
            "falafel":"greek",
            "mexican":"mexican",
            "tacos":"mexican",
            "mideastern":"mediterranean",
            "egyptian":"african",
            "seafood":"seafood",
            "sushi":"japanese",
            "noodles": "japanese",
            "newmexican":"mexican",
            "mongolian":"chinese",
            "taiwanese":"chinese",
            "tapas":"italian",
            "tapasmallplates":"italian",
            "thai":"thai",
            "turkish":"turkish",
            "ukrainian":"ukrainian",
            "steak":"tradamerican",
            "singaporean":"chinese",
            "lebanese":"arabian",
            "moroccan":"moroccan",
            "uzbek":"asianfusion",
            "tex-mex":"mexican",
            "syrian":"syrian",
            "supperclubs": "newamerican",
            "nicaraguan":"caribbean",
            "pakistani":"syrian",
            "panasian":"asianfusion",
            "persian":"persian",
            "peruvian":"peruvian",
            "polish":"polish",
            "popuprestaurants": "newamerican",
            "spanish":"spanish",
            "portuguese":"portuguese",
            "poutineries":"fastfood",
            "russian":"russian",
            "scandinavian":"scottish",
            "scottish":"scottish",
            "slovakian":"italian",
            "soulfood":"fastfood",
            "soup": "italian",
            "southern": "latin",
            "srilankan":"indian",
            "modern_european":"german",
            "pizza": "italian",
            "sandwiches":"fastfood",
            "salad": "vegetarian",
            "vegan":"vegetarian",
            "vegetarian":"vegetarian",
            "vietnamese":"vietnamese",
            "waffles":"tradamerican",
            "wraps":"fastfood"}
